$PiHost = "host"
$PiUser = "user"
$TargetPath = "/path/app.jar"
$SshKey = "$env:USERPROFILE\.ssh\id_rsa"
$DisplayName = "Webserver Display Name"
$BootstrapAdminUsername = "admin"
$BootstrapAdminPassword = "change-me-before-first-production-start"
$ServiceName = "webserver"
$ServerPort = 8080
$InstallSystemdService = $true
$RestartSystemdService = $true
