$PiHost = "host"
$PiUser = "user"
$TargetPath = "/path/app.jar"
$SshKey = "$env:USERPROFILE\.ssh\id_rsa"
$BootstrapAdminUsername = "admin"
$BootstrapAdminPassword = "change-me-before-first-production-start"
