spring.application.name=Webserver
spring.datasource.url=jdbc:sqlite:./data/webserver.sqlite
spring.datasource.driver-class-name=org.sqlite.JDBC
app.bootstrap-admin.username=admin
app.bootstrap-admin.password=${BOOTSTRAP_ADMIN_PASSWORD:admin123}
