server.port=8080
app.display-name=${APP_DISPLAY_NAME:}
spring.datasource.url=jdbc:sqlite:./data/webserver.sqlite
spring.datasource.driver-class-name=org.sqlite.JDBC
app.bootstrap-admin.username=${BOOTSTRAP_ADMIN_USERNAME:admin}
app.bootstrap-admin.password=${BOOTSTRAP_ADMIN_PASSWORD:}
server.address=127.0.0.1

spring.thymeleaf.cache=true

logging.file.name=/var/log/heimserver/heimserver.log
